// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbDdQ_c_qZ6ueyejKQ3uzlHo28hG2JRIA',
    appId: '1:335422341616:web:e1de1eab5f751507995d35',
    messagingSenderId: '335422341616',
    projectId: 'flutterapp-94f84',
    authDomain: 'flutterapp-94f84.firebaseapp.com',
    storageBucket: 'flutterapp-94f84.appspot.com',
    measurementId: 'G-GJ84SLP5B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0hspVBI6AmFor24onvs2Ngh4LJJCJJDo',
    appId: '1:335422341616:android:b6a46acf3becf406995d35',
    messagingSenderId: '335422341616',
    projectId: 'flutterapp-94f84',
    storageBucket: 'flutterapp-94f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiw8ISGRXReJVZCZ7L1KMSU_wvMwRsVs',
    appId: '1:335422341616:ios:33fbefbd0deb1e07995d35',
    messagingSenderId: '335422341616',
    projectId: 'flutterapp-94f84',
    storageBucket: 'flutterapp-94f84.appspot.com',
    iosBundleId: 'com.example.sahyogi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFiw8ISGRXReJVZCZ7L1KMSU_wvMwRsVs',
    appId: '1:335422341616:ios:2b116b6764cfeb95995d35',
    messagingSenderId: '335422341616',
    projectId: 'flutterapp-94f84',
    storageBucket: 'flutterapp-94f84.appspot.com',
    iosBundleId: 'com.example.sahyogi.RunnerTests',
  );
}
